from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass(frozen=True, slots=True)
class Event:
    """Base event exchanged between trading-system components."""

    timestamp: datetime


@dataclass(frozen=True, slots=True)
class MarketEvent(Event):
    """Event generated from incoming market data."""

    symbol: str
    data: Any


@dataclass(frozen=True, slots=True)
class OrderEvent(Event):
    """Event related to order lifecycle changes."""

    order_id: str
    data: Any


@dataclass(frozen=True, slots=True)
class FillEvent(Event):
    """Event generated when an order receives an execution."""

    order_id: str
    data: Any


@dataclass(frozen=True, slots=True)
class RiskEvent(Event):
    """Event generated by the risk engine."""

    reason: str
    blocked: bool

@dataclass(frozen=True, slots=True)
class BarEvent(Event):
    """Event generated when a market-data bar is finalized."""
    symbol: str
    data: Any

    